MicrosoftMVC/Models/ErrorViewModel.cs
namespace MicrosoftMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MicrosoftMVC/Models/Lutador.cs
namespace MicrosoftMVC.Models
{
    public class Lutador
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public int ArtesMarciais { get; set; }
        public int TotalLutas { get; set; }
        public int Derrotas { get; set; }
        public int Vitorias { get; set; }
    }

}

MicrosoftMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MicrosoftMVC.Models;
using System.Diagnostics;

namespace MicrosoftMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MicrosoftMVC/Controllers/LutadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MicrosoftMVC.Data;
using MicrosoftMVC.Models;

namespace MicrosoftMVC.Controllers
{
    public class LutadorController : Controller
    {
        private readonly MicrosoftMVCContext _context;

        public LutadorController(MicrosoftMVCContext context)
        {
            _context = context;
        }

        // GET: Lutador
        public async Task<IActionResult> Index()
        {
              return _context.Lutador != null ? 
                          View(await _context.Lutador.ToListAsync()) :
                          Problem("Entity set 'MicrosoftMVCContext.Lutador'  is null.");
        }

        // GET: Lutador/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Lutador == null)
            {
                return NotFound();
            }

            var lutador = await _context.Lutador
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lutador == null)
            {
                return NotFound();
            }

            return View(lutador);
        }

        // GET: Lutador/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lutador/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Idade,ArtesMarciais,TotalLutas,Derrotas,Vitorias")] Lutador lutador)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lutador);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lutador);
        }

        // GET: Lutador/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Lutador == null)
            {
                return NotFound();
            }

            var lutador = await _context.Lutador.FindAsync(id);
            if (lutador == null)
            {
                return NotFound();
            }
            return View(lutador);
        }

        // POST: Lutador/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Idade,ArtesMarciais,TotalLutas,Derrotas,Vitorias")] Lutador lutador)
        {
            if (id != lutador.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lutador);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LutadorExists(lutador.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lutador);
        }

        // GET: Lutador/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Lutador == null)
            {
                return NotFound();
            }

            var lutador = await _context.Lutador
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lutador == null)
            {
                return NotFound();
            }

            return View(lutador);
        }

        // POST: Lutador/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Lutador == null)
            {
                return Problem("Entity set 'MicrosoftMVCContext.Lutador'  is null.");
            }
            var lutador = await _context.Lutador.FindAsync(id);
            if (lutador != null)
            {
                _context.Lutador.Remove(lutador);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LutadorExists(int id)
        {
          return (_context.Lutador?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MicrosoftMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MicrosoftMVC/Views/Lutador/Create.cshtml
@model MicrosoftMVC.Models.Lutador

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Lutador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtesMarciais" class="control-label"></label>
                <input asp-for="ArtesMarciais" class="form-control" />
                <span asp-validation-for="ArtesMarciais" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalLutas" class="control-label"></label>
                <input asp-for="TotalLutas" class="form-control" />
                <span asp-validation-for="TotalLutas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Derrotas" class="control-label"></label>
                <input asp-for="Derrotas" class="form-control" />
                <span asp-validation-for="Derrotas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vitorias" class="control-label"></label>
                <input asp-for="Vitorias" class="form-control" />
                <span asp-validation-for="Vitorias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MicrosoftMVC/Views/Lutador/Delete.cshtml
@model MicrosoftMVC.Models.Lutador

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lutador</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArtesMarciais)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArtesMarciais)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalLutas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalLutas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Derrotas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Derrotas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vitorias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vitorias)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MicrosoftMVC/Views/Lutador/Details.cshtml
@model MicrosoftMVC.Models.Lutador

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Lutador</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Idade)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Idade)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ArtesMarciais)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ArtesMarciais)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalLutas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalLutas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Derrotas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Derrotas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vitorias)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Vitorias)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MicrosoftMVC/Views/Lutador/Edit.cshtml
@model MicrosoftMVC.Models.Lutador

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Lutador</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Idade" class="control-label"></label>
                <input asp-for="Idade" class="form-control" />
                <span asp-validation-for="Idade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtesMarciais" class="control-label"></label>
                <input asp-for="ArtesMarciais" class="form-control" />
                <span asp-validation-for="ArtesMarciais" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalLutas" class="control-label"></label>
                <input asp-for="TotalLutas" class="form-control" />
                <span asp-validation-for="TotalLutas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Derrotas" class="control-label"></label>
                <input asp-for="Derrotas" class="form-control" />
                <span asp-validation-for="Derrotas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Vitorias" class="control-label"></label>
                <input asp-for="Vitorias" class="form-control" />
                <span asp-validation-for="Vitorias" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MicrosoftMVC/Views/Lutador/Index.cshtml
@model IEnumerable<MicrosoftMVC.Models.Lutador>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Idade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArtesMarciais)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalLutas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Derrotas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Vitorias)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArtesMarciais)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalLutas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Derrotas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vitorias)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MicrosoftMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MicrosoftMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MicrosoftMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MicrosoftMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lutador" asp-action="Index">Torneio de luta</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MicrosoftMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>